### ISSUE TITLE
iter.Seq and naming changes

### ISSUE THREAD

**Issue by pd93** [elliotchance/orderedmap#44]
It would be nice to have the following methods available:

```go
func (m *OrderedMap[K, V]) All() iter.Seq2[K, V] {...}
func (m *OrderedMap[K, V]) Keys() iter.Seq[K] {...}
func (m *OrderedMap[K, V]) Values() iter.Seq[V] {...}
```

These would line up nicely with the newly implemented [`All`](https://pkg.go.dev/maps#All), [`Keys`](https://pkg.go.dev/maps#Keys) and [`Values`](https://pkg.go.dev/maps#Values) functions in the standard `maps` package. Adding the two `iter.Seq` methods also allows for compatibility with [`slices.Collect`](https://pkg.go.dev/slices#Collect).

Unfortunately, `Keys()` conflicts with the existing pre-iterators method and would require a major version change (or a different name). For the long-term I think the package would benefit from this consistency with the standard library. Also, the current version of the `Keys()` method can be inefficient on large maps and moving to an iterator by default instead is a good API improvement IMO.

Some other points:

- `All()` would be identical to the current `Iterator()` method, but again, would be more idiomatic.
- `Values()` was never implemented previously so no problems adding this.
- As we currently have `ReverseIterator()` maybe we should have `AllFromFront()` and `AllFromBack()` instead. This is both idiomatic and consistent with the naming in this package. `All()` could be an alias for `AllFromFront()`.

I understand that a major API change isn't always desirable, but I believe these changes will benefit the design in the long-term. I've created a branch with the proposed changes [in my fork](https://github.com/pd93/orderedmap/commit/d80adfe0db1369a3b5bc3c8148c4362385833229).

**Comment by elliotchance** [comment]
Yes, I'd be open to a v3 with those changes. If that's the case theres no reason to keep any existing function names. Happy to accept a PR from your fork. 😄
